apiVersion: v1
kind: Service
metadata:
  labels:
    app: pengwin
  name: pengwin
  namespace: default
spec:
  ports:
  - nodePort: 30149
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: pengwin
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.241
